add DropdownButton
KlubJagiellonski/pola-barcodes pull request #12
Opened 2024-07-05 12:12 UTC by D3bi7

<img width="1433" alt="Zrzut ekranu 2024-07-5 o 14 12 31" src="https://github.com/KlubJagiellonski/pola-barcodes/assets/167427782/e3bb3537-2db1-4cbe-bec2-baaedbceaec5">

2024-07-05 13:58 UTC, WezSieTato requested changes

2024-07-05 13:58 UTC, WezSieTato commented on lib/barcodes_panel.dart
> +            value: 'EAN13',
Zamiast trzymać wartość w postaci tekstu zrób enuma do tego `BarcodeType` https://dart.dev/language/enums

2024-07-08 08:08 UTC, D3bi7 commented
<img width="1434" alt="Zrzut ekranu 2024-07-8 o 09 51 28" src="https://github.com/KlubJagiellonski/pola-barcodes/assets/167427782/bd1443dd-78b9-47bb-919c-c940cf8c3d8d">
<img width="325" alt="Zrzut ekranu 2024-07-8 o 09 51 49" src="https://github.com/KlubJagiellonski/pola-barcodes/assets/167427782/eeaaedd1-a840-408d-83fc-78552912db74">

2024-07-09 07:04 UTC, WezSieTato approved these changes

2024-07-10 12:30 UTC, merged