Feature/13
KlubJagiellonski/pola-barcodes pull request #14
Opened 2024-07-10 12:05 UTC by D3bi7

<img width="1437" alt="Zrzut ekranu 2024-07-10 o 14 01 49" src="https://github.com/KlubJagiellonski/pola-barcodes/assets/167427782/7d166167-6165-46b8-b16c-4eb0ff1575db">

2024-07-11 16:52 UTC, WezSieTato requested changes

2024-07-11 16:52 UTC, WezSieTato commented on lib/barcodes_panel.dart
> +          BarcodeWidget(
Zamiast robić try i próbować robić widget z którego nie będziesz korzystać możesz użyć funkcji isValid https://pub.dev/documentation/barcode_widget/latest/barcode_widget/Barcode/isValid.html

Wtedy kod wyglądałby tak
```dart
if (_descriptionError == null && _dataError == null && barcodeType.isValid == false) {
          _dataError = "Nieprawidłowy kod kreskowy";
}
```

2024-07-11 18:52 UTC, WezSieTato commented
Close #13

2024-07-15 08:40 UTC, D3bi7 commented
<img width="1191" alt="Zrzut ekranu 2024-07-15 o 10 39 54" src="https://github.com/user-attachments/assets/3527222b-49f2-4cdb-9c43-e57b628d4849">

2024-07-15 11:07 UTC, D3bi7 commented
<img width="1193" alt="Zrzut ekranu 2024-07-15 o 13 06 07" src="https://github.com/user-attachments/assets/324235c9-15ac-4f54-8e94-ab6909e4f31a">
<img width="1181" alt="Zrzut ekranu 2024-07-15 o 13 04 28" src="https://github.com/user-attachments/assets/73657216-f24c-4714-afe2-518830d2b181">

<img width="1178" alt="Zrzut ekranu 2024-07-15 o 13 05 49" src="https://github.com/user-attachments/assets/68ff481e-6e4a-4d8f-a9dd-9646ef7ce937">

2024-07-15 11:12 UTC, WezSieTato requested changes

2024-07-15 11:12 UTC, WezSieTato commented on lib/barcodes_panel.dart
> +              // errorText: errorText,
Komentarze do kosza.

2024-07-15 11:12 UTC, WezSieTato commented on lib/barcodes_panel.dart
> +                padding: const EdgeInsets.only(top: 20.0), // Wyrównanie przycisku z polami tekstowymi
Często pojawia się tu 20 i 10, które opisują te same wartości. Stwórz na nie prywatną klasę Constants i zamiast wartości wpisanej ręcznie daj np. `Constants.errorHeight`

2024-07-15 11:12 UTC, WezSieTato commented on lib/barcodes_panel.dart
> +                padding: const EdgeInsets.only(top: 20.0), // Wyrównanie przycisku z polami tekstowymi
To samo z 10 która jest wyżej.

2024-07-15 12:54 UTC, WezSieTato requested changes

2024-07-15 12:54 UTC, WezSieTato commented on lib/barcodes_panel.dart
> +  static const double bottomPadding = 20.0;
`errorHeight` i `bottomPadding` to jest to samo w tym przypadku. Padding dajesz, ze względu na wysokość błedu. Wybierz jedno, drugie wywal.

2024-07-16 07:06 UTC, WezSieTato requested changes

2024-07-16 07:06 UTC, WezSieTato commented on lib/barcodes_panel.dart
> +                .errorHeight, // Zarezerwowanie miejsca na komunikat o błędzie
Komentarze do kosza. Po usunięcie odpal formaterr.

2024-07-16 07:10 UTC, WezSieTato approved these changes

2024-07-16 07:14 UTC, merged