ability to generate barcodes in EAN13 format and add them to the existing list of codes on the website
KlubJagiellonski/pola-barcodes pull request #9
Opened 2024-07-04 07:55 UTC by D3bi7

<img width="1196" alt="Zrzut ekranu 2024-07-4 o 09 53 59" src="https://github.com/KlubJagiellonski/pola-barcodes/assets/167427782/c9c747ba-71f4-4036-8651-fb7fa985df0e">

2024-07-04 07:56 UTC, D3bi7 commented
fix#2

2024-07-05 08:47 UTC, WezSieTato requested changes

2024-07-05 08:47 UTC, WezSieTato commented on lib/barcodes_list_view.dart
> +              Expanded(
To powinno być wyniesione do oddzielnej funkcji tak jak było wcześniej w `BarcodesPage`

2024-07-05 08:47 UTC, WezSieTato commented on lib/barcodes_list_view.dart
> +class BarcodeItemWidget extends StatelessWidget {
Wynieś tą klasę do nowego pliku.

2024-07-05 08:47 UTC, WezSieTato commented on lib/barcodes_page.dart
> +}
Na końcu pliku ma być zawsze pusta linia

2024-07-05 08:47 UTC, WezSieTato commented on lib/barcodes_panel.dart
> +              Expanded(
To można wynieść do oddzielnej funkcji bo kod jest prawie identyczny co niżej.
Może to wyglądać tak:
```
 _textField(_descriptionController, "Opis"),
   const SizedBox(width: 10),
 _textField(_dataController, "Kod kreskowy");
```

2024-07-05 08:47 UTC, WezSieTato commented on lib/barcodes_panel.dart
> +}
Pusta linia na koncu pliku powinna być

2024-07-05 11:07 UTC, WezSieTato approved these changes

2024-07-05 11:09 UTC, merged